KeFAStOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('',include('cart.urls')),
    path('order/',include('order.urls')),
    path('',include('eshop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
  url(r'^shopping-cart/$',views.cart_detail, name='cart_detail'),
  url(r'^add/(?P<product_id>\d+)/$',views.cart_add, name='cart_add'),
  url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove, name='cart_remove'),
]

eshop/urls.py
from django.conf.urls import url

from django.urls import path

from . import views

app_name = 'eshop'

urlpatterns = [
  path('home/', views.index, name='home'),
  path('help/', views.faqsDetail, name='help'),
  path('about/', views.aboutDetail, name='about_detail'),
  path('contact/', views.contactDetail, name='contact_detail'),
  path('product/', views.productPage,name="product"),
  url(r'^(?P<category_slug>[-\w]+)/$', views.productPage, name='product-by-category'),
  url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/(?P<inventory_id>[-\w]+)$',views.product_detail,name='product-detail'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
  path('order/', views.order_create, name='order')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1, 50)]

class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES, coerce = int)
  update = forms.BooleanField(required = False, initial = False, widget = forms.HiddenInput)
  

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from eshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
  return redirect('cart:cart_detail')

def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')

def cart_detail(request):
  cart = Cart(request)
  for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
  return render(request,'cart/shopping-cart.html',{'cart': cart})

cart/templates/cart/shopping-cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %} Shopping Cart {% endif %}
{% endblock %}

{% block content %}
  <!--breadcrumb-->
  <div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-80 p-lr-0-lg">
      <a href="{% url 'eshop:home' %}" class="stext-109 cl8 hov-cl1 trans-04">
        HOME
        <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
      </a>
      <span class="stext-109 cl4">
        SHOPPING CART
      </span>
    </div>
  </div>
  <!--Shopping Cart-->
  <form class="bg0 p-t-25 p-b-85">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
          <div class="m-l-25 m-r--38 m-lr-0-xl">
            <div class="wrap-table-shopping-cart">
              <table class="table-shopping-cart">
                <tr class="table_head">
                  <th class="column-1">Product</th>
                  <th class="column-2"></th>
                  <th class="column-3">Price</th>
                  <th class="column-4">Quantity</th>
                  <th class="column-5">Total</th>
                  <th class="column-6">Remove</th>
                </tr>
                {% for item in cart %}
                  {% with product=item.product %}
                    <tr class="table_row">
                      <td class="column-1">
                        <div class="how-itemcart1">
                          <a href="{{ product.get__absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/item-cart-04.jpg' %}{% endif %}" alt="Image"></a>
                        </div>
                      </td>
                      <td class="column-2">{{ product.name }}</td>
                      <td class="column-3">Kshs. {{ item.price }}</td>
                      <td class="column-4">
                        <div class="wrap-num-product flex-w m-l-auto m-r-0">
                          <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                          </form>
                        </div>
                      </td>
                      <td class="column-5">Kshs. {{ item.total_price }}</td>
                      <td class="column-6"><a href="{% url 'cart:cart_remove' product.id %}">X</a></td>
                    </tr>
                  {% endwith %}
                {% endfor %}
              </table>
            </div>
            <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
              <div class="flex-w flex-m m-r-20 m-tb-5">
                <a href="{% url 'eshop:product' %}"><div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">
                    CONTINUE SHOPPING
                </div></a>
              </div>
              <div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">UPDATE CART</div>
            </div>
          </div>
        </div>
        <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
          <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
            <h4 class="mtext-109 cl2 p-b-30">
             SHOPPING CART
            </h4>
            <div class="flex-w flex-t p-t-27 p-b-33">
              <div class="size-208">
                <span class="mtext-101 cl2">
                  TOTAL:
                </span>
              </div>
              <div class="size-209 p-t-1">
                <span class="mtext-110 cl2">
                  Kshs. {{ cart.get_total_price }}
                </span>
              </div>
            </div>
            <a href="{% url 'order:order' %}"><button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">PROCEED TO CHECKOUT</button></a>
          </div>
        </div>
      </div>
    </div>
  </form>
{% endblock %}